create table "public"."verification_tokens" (
    "user_id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."verification_tokens" enable row level security;

alter table "public"."users" add column "is_verified" boolean default false;

CREATE UNIQUE INDEX verification_tokens_pkey ON public.verification_tokens USING btree (user_id, created_at);

alter table "public"."verification_tokens" add constraint "verification_tokens_pkey" PRIMARY KEY using index "verification_tokens_pkey";

alter table "public"."verification_tokens" add constraint "verification_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."verification_tokens" validate constraint "verification_tokens_user_id_fkey";

grant delete on table "public"."verification_tokens" to "anon";

grant insert on table "public"."verification_tokens" to "anon";

grant references on table "public"."verification_tokens" to "anon";

grant select on table "public"."verification_tokens" to "anon";

grant trigger on table "public"."verification_tokens" to "anon";

grant truncate on table "public"."verification_tokens" to "anon";

grant update on table "public"."verification_tokens" to "anon";

grant delete on table "public"."verification_tokens" to "authenticated";

grant insert on table "public"."verification_tokens" to "authenticated";

grant references on table "public"."verification_tokens" to "authenticated";

grant select on table "public"."verification_tokens" to "authenticated";

grant trigger on table "public"."verification_tokens" to "authenticated";

grant truncate on table "public"."verification_tokens" to "authenticated";

grant update on table "public"."verification_tokens" to "authenticated";

grant delete on table "public"."verification_tokens" to "service_role";

grant insert on table "public"."verification_tokens" to "service_role";

grant references on table "public"."verification_tokens" to "service_role";

grant select on table "public"."verification_tokens" to "service_role";

grant trigger on table "public"."verification_tokens" to "service_role";

grant truncate on table "public"."verification_tokens" to "service_role";

grant update on table "public"."verification_tokens" to "service_role";


