create table "public"."rooms" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" character varying,
    "is_deleted" boolean default false,
    "user_id" integer not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."verification_tokens" (
    "user_id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "token" uuid not null
);


alter table "public"."users" add column "is_verified" boolean default false;

alter table "public"."users" add column "salt" text not null default ''::text;

CREATE UNIQUE INDEX rooms_pkey ON public.rooms USING btree (id);

CREATE UNIQUE INDEX verification_tokens_pkey ON public.verification_tokens USING btree (created_at, user_id, token);

alter table "public"."rooms" add constraint "rooms_pkey" PRIMARY KEY using index "rooms_pkey";

alter table "public"."verification_tokens" add constraint "verification_tokens_pkey" PRIMARY KEY using index "verification_tokens_pkey";

alter table "public"."rooms" add constraint "rooms_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."rooms" validate constraint "rooms_user_id_fkey";

alter table "public"."verification_tokens" add constraint "verification_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."verification_tokens" validate constraint "verification_tokens_user_id_fkey";

grant delete on table "public"."rooms" to "anon";

grant insert on table "public"."rooms" to "anon";

grant references on table "public"."rooms" to "anon";

grant select on table "public"."rooms" to "anon";

grant trigger on table "public"."rooms" to "anon";

grant truncate on table "public"."rooms" to "anon";

grant update on table "public"."rooms" to "anon";

grant delete on table "public"."rooms" to "authenticated";

grant insert on table "public"."rooms" to "authenticated";

grant references on table "public"."rooms" to "authenticated";

grant select on table "public"."rooms" to "authenticated";

grant trigger on table "public"."rooms" to "authenticated";

grant truncate on table "public"."rooms" to "authenticated";

grant update on table "public"."rooms" to "authenticated";

grant delete on table "public"."rooms" to "service_role";

grant insert on table "public"."rooms" to "service_role";

grant references on table "public"."rooms" to "service_role";

grant select on table "public"."rooms" to "service_role";

grant trigger on table "public"."rooms" to "service_role";

grant truncate on table "public"."rooms" to "service_role";

grant update on table "public"."rooms" to "service_role";

grant delete on table "public"."verification_tokens" to "anon";

grant insert on table "public"."verification_tokens" to "anon";

grant references on table "public"."verification_tokens" to "anon";

grant select on table "public"."verification_tokens" to "anon";

grant trigger on table "public"."verification_tokens" to "anon";

grant truncate on table "public"."verification_tokens" to "anon";

grant update on table "public"."verification_tokens" to "anon";

grant delete on table "public"."verification_tokens" to "authenticated";

grant insert on table "public"."verification_tokens" to "authenticated";

grant references on table "public"."verification_tokens" to "authenticated";

grant select on table "public"."verification_tokens" to "authenticated";

grant trigger on table "public"."verification_tokens" to "authenticated";

grant truncate on table "public"."verification_tokens" to "authenticated";

grant update on table "public"."verification_tokens" to "authenticated";

grant delete on table "public"."verification_tokens" to "service_role";

grant insert on table "public"."verification_tokens" to "service_role";

grant references on table "public"."verification_tokens" to "service_role";

grant select on table "public"."verification_tokens" to "service_role";

grant trigger on table "public"."verification_tokens" to "service_role";

grant truncate on table "public"."verification_tokens" to "service_role";

grant update on table "public"."verification_tokens" to "service_role";


